# Promise 链

`then` 和 `catch` 永远会返回一个 Promise 对象

::: tip

当 `then` 和 `catch`

- 没有 `return`
  - 返回一个 `state` 为 `"padding"`， `result` 为 `undefined` 的 `promise`
- `return a`
  - 返回一个 `state` 为 `"fullfilled"`， `result` 为 `a` 的 `promise`
- 抛出错误
  - 返回一个 `state` 为 `"rejected"`， `result` 为抛出的错误的 `promise`
- `return new Promise`
  - 返回这个 `promise`

:::

```js
const promise = new Promise((resolve, reject) => {
  resolve(1);
});

promise
  .then((res1) => {
    console.log(res1); // 1
    // 没有 return
    // 返回一个 `state` 为 `"padding"`， `result` 为 `undefined` 的 promise
  })
  .then((res2) => {
    console.log(res2);
    return "a";
    //返回一个 `state` 为 `"fullfilled"`， `result` 为 `a` 的 promise
  })
  .then((res3) => {
    console.log(res3); // 'a'
    throw "我是一个错误";
    // 返回一个 `state` 为 `"rejected"`， `result` 为 "我是一个错误" 的 promise
  })
  .catch((err) => {
    console.log(err); // "我是一个错误"
    return new Promise((resolve, reject) => {
      resolve(5);
    });
    // 返回一个 state 为 "fulfilled", result 为 5 的promise
  })
  .then((res4) => {
    console.log(res4); // 5
  });
```
